### ISSUE TITLE
not able to use library 

### ISSUE THREAD

**Issue by nikitamarysoloman** [mkaflowski/HybridMediaPlayer#1]
Failed to resolve: com.github.mkaflowski:HybridMediaPlayer:1.x 
please help

**Comment by mkaflowski** [comment]
You need to change x to release number.

**Comment by nikitamarysoloman** [comment]
Let me know which are the most updated ones

**Comment by nikitamarysoloman** [comment]
ok iam using 1.1.5 thankyou

**Comment by Zulqurnain** [comment]
i am unable to resolve this too compile 'com.github.mkaflowski:HybridMediaPlayer:1.2.4'
