### ISSUE TITLE
How can I resolve this?

### ISSUE THREAD

**Issue by provizor54** [mkaflowski/HybridMediaPlayer#2]
Error:(51, 13) Failed to resolve: com.github.mkaflowski:HybridMediaPlayer:1.x
<a href="openFile:C:/Users/Pole/AndroidStudioProjects/QWERTY2/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by mkaflowski** [comment]
https://github.com/mkaflowski/HybridMediaPlayer/issues/1
